### ISSUE TITLE
Ошибка при запросе - location is not defined.

### ISSUE THREAD

**Issue by MaksSaga** [VKCOM/vkid-web-sdk#10]
Написал код следуя инструкции VK SDK (web), использовал nest js:

```
import { Injectable, OnModuleInit } from '@nestjs/common'
import { ConfigService } from '@nestjs/config'
import * as VKID from '@vkid/sdk'

@Injectable()
export class VkService implements OnModuleInit {
  constructor(private readonly configService: ConfigService) {}

  onModuleInit(): any {
    VKID.Config.set({
      app: this.configService.get<number>('VK_APP_ID'), // Идентификатор приложения.
      redirectUrl: this.configService.get<string>('VK_APP_REDIRECT_URL'), // Адрес для перехода после авторизации.
    })
  }

  auth(): any {
    VKID.Auth.login()
  }
}
```

сам контроллер:

```
import { Controller, Get } from '@nestjs/common'
import { VkService } from './vk.service'

@Controller('auth/vk')
export class VkController {
  constructor(private readonly vkService: VkService) {}

  @Get()
  auth() {
    this.vkService.auth()
  }
}
```

и каждый раз как я пробую авторизоваться (не то что бы даже авторизоваться мне и выбора не дают, просто банально перехожу по роуту auth/vk) я, получаю ответ от сервера:
```
{
"statusCode": 500,
"message": "Internal server error"
}
```

и в консоль получаю:
```
ReferenceError: location is not defined
at Auth.login (D:\WebStorm\production\panda\server\node_modules\@vkid\sdk\dist-sdk\cjs\auth\auth.js:36:9)
at VkService.auth (D:\WebStorm\production\panda\server\src\modules\auth\vk\vk.service.ts:17:15)
at VkController.auth (D:\WebStorm\production\panda\server\src\modules\auth\vk\vk.controller.ts:10:20)
at D:\WebStorm\production\panda\server\node_modules\[@nestjs](https://vk.com/nestjs)\core\router\router-execution-context.js:38:29
at InterceptorsConsumer.intercept (D:\WebStorm\production\panda\server\node_modules\[@nestjs](https://vk.com/nestjs)\core\interceptors\interceptors-consumer.js:12:20)
at D:\WebStorm\production\panda\server\node_modules\[@nestjs](https://vk.com/nestjs)\core\router\router-execution-context.js:46:60
at D:\WebStorm\production\panda\server\node_modules\[@nestjs](https://vk.com/nestjs)\core\router\router-proxy.js:9:23
at Layer.handle [as handle_request] (D:\WebStorm\production\panda\server\node_modules\express\lib\router\layer.js:95:5)
at next (D:\WebStorm\production\panda\server\node_modules\express\lib\router\route.js:144:13)
at Route.dispatch (D:\WebStorm\production\panda\server\node_modules\express\lib\router\route.js:114:3)
```

Как быть, какие решения ? Пытался гуглить - бесполезно.

(прошу учесть, что пытался как из localhost стучаться, так и с облачного сервера)

**Comment by Thisman** [comment]
Привет! Похоже, код SDK вызывается в окружении nodejs, где нет объекта location. Правильно понимаю, что вы хотите прямо с бекенда делать редирект на авторизацию VK ID?

**Comment by MaksSaga** [comment]
> Привет! Похоже, код SDK появляется в созданном nodejs, где нет местоположения объекта. понимаю, что вы прямо с бекенда хотите делать редирект по авторизации VK ID?

Да, правильно. Так и хочу.

**Comment by Thisman** [comment]
Привет! Наше библиотека пока что не поддерживает в окружении nodejs. Могу предложить вариант авторизации по прямой ссылке, которую можно реализовать на бекенде https://id.vk.com/about/business/go/docs/ru/vkid/latest/vk-id/link-connection/web

Вместо
```
location.assign(`https://id.vk.com/auth?${query}`);
```
нужно будет использовать редирект Next.js

Касательно поддержки для nodejs - обдумаем эту возможность

**Comment by MaksSaga** [comment]
> > Да, правильно. Так и хочу.
> 
> Привет! Наш SDK пока не поддерживает окружение nodejs. Могу предложить вариант авторизации по прямой ссылке, который можно реализовать на бекенде https://id.vk.com/about/business/go/docs/ru/vkid/latest/vk-id/link-connection/web
> 
> Вместо этого
> 
> ```
> location.assign(`https://id.vk.com/auth?${query}`);
> ```
> 
> нужно будет использовать редирект Next.js
> 
> Касательная поддержка nodejs - обдумываем эту возможность

Я вас понял, спасибо, я уверен, что если вы прейдёте к решению, адаптировать ваше приложение под node js, это многократно облегчит работу с авторизацией через ВК. Спасибо еще раз.
